#!/usr/bin/env bash
# Script kills another script running in another terminal (need -f to find pid)
#a Bash script that stops 4-to_infinity_and_beyond process.

kill "$(pgrep -f "4-to_infinity_and_beyond")"
