#!/usr/bin/env bash
# Script kills another script running in another terminal (need -f to find pid)
#We stopped our 4-to_infinity_and_beyond process using ctrl+c in the previous task,#there is actually another way to do this.
#Write a Bash script that stops 4-to_infinity_and_beyond process.

kill "$(pgrep -f "4-to_infinity_and_beyond")"
