#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59
d=0
while [ "$d" -le 12 ]
do
    echo "Hour: $d"
    (( d++ ))

    a=1
    while [ "$a" -le 59 ]
    do
	echo "$a"
	(( a++ ))
    done
done
