#!/usr/bin/env bash
#Update and Install nginx web server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
#Create Hello World html file
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
#configure nginx to listen on port 80
echo "server {
    listen 80;
    add_header X-Served-By $HOSTNAME;
    location / {
        root /etc/nginx/html;
        index index.html;
    }
    location /redirect {
        return 301 https://en.wikipedia.org/wiki/The_Spanish_Inquisition_(Monty_Python);
    }
    error_page 404 /404.html;
}" > /etc/nginx/sites-available/default
#restart nginx
sudo service nginx restart
